# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    resource_group_name   = "terraform-backend"  # Update with your resource group name
    storage_account_name  = "cloudutsuktfstatestgacc"       # Update with your storage account name
    container_name        = "terraform-state"                    # Update with your container name for state files
    key                   = "./terraform.tfstate"
  }
}
