# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_version = ">= 1.9.8"
      
      required_providers {
          azurerm = {
          source  = "hashicorp/azurerm"
          version = ">= 4.7.0"
          }
      }
    }

    provider "azurerm" {
        features {
          resource_group {
            prevent_deletion_if_contains_resources = false
          }
        }  # Required block for the Azure provider
    }

    provider "azuread" {
    }
