version: 3

tasks:
  one-click-deploy:
    desc: "Deploy the application to the cloud"
    cmds:
      - ./entrypoint.py 
  
  git-push:
    desc: Git Add, Commit and Push
    cmds:
      - git status
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push    
    