apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: jira-alert-secrets
  namespace: jira
spec:
  provider: azure
  secretObjects:                       # SecretObject defines the desired state of synced Kubernetes secret objects
  - secretName: jira-alert-secrets
    type: Opaque
    data:
    - objectName: jiraapiurl
      key: API_URL
    - objectName: jirauser
      key: JIRA_USER
    - objectName: jirapassword
      key: JIRA_PASSWORD
  parameters:
    usePodIdentity: "false"            # Set to "true" if using managed identities
    useVMManagedIdentity: "true"      # Set to "true" if using VM managed identity
    userAssignedIdentityID: "c824a3b2-96c4-4aea-abb2-24ff3aacfb0d"
    keyvaultName: "ops-utility-secrets-kv" # Replace with your Key Vault name
    cloudName: ""                      # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: jiraapiurl
          objectType: secret           # object types: secret, key, or cert
        - |
          objectName: jirauser
          objectType: secret
        - |
          objectName: jirapassword
          objectType: secret
    tenantId: "fc8e13c0-422c-4c55-b3ea-ca318e6cac32"        # Replace with your tenant ID
