apiVersion: v1
kind: ConfigMap
metadata:
  name: jiralert-config
  namespace: jira
data:
  jiralert.yml: |-
    # Global defaults, applied to all receivers where not explicitly overridden. Optional.
    template: jiralert.tmpl

    defaults:
      # API access fields.
      api_url: $(API_URL)
      user: $(JIRA_USER)
      password: $(JIRA_PASSWORD)

      # The type of JIRA issue to create. Required.
      issue_type: Bug
      # Issue priority. Optional.
      priority: High
      # Go template invocation for generating the summary. Required.
      summary: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.alertname }} {{ if .GroupLabels.CustomerName }} {{ .GroupLabels.CustomerName }} - {{ end }}'
      # Go template invocation for generating the description. Optional.
      description: '{{ template "jira.description" . }}'
      # State to transition into when reopening a closed issue. Required.
      reopen_state: "REOPEN"
      # Do not reopen issues with this resolution. Optional.
      wont_fix_resolution: "Won't Fix"
      # Amount of time after being closed that an issue should be reopened, after which, a new issue is created.
      # Optional (default: always reopen)
      reopen_duration: 30d

    # Receiver definitions. At least one must be defined.
    # Receiver names must match the Alertmanager receiver names. Required.
    receivers:
    - name: 'jiraintegration'
      project: 'GTA'
      issue_type: Task
      components: ['Operations']
      static_labels: []
      reopen_state: "Backlog"
      reopen_duration: 72h
      update_in_comment: true
      #fields:
      #  Customers: { .GroupLabels.CustomerName }
      auto_resolve:
        state: 'Done'
      add_group_labels: false
  jiralert.tmpl: |-
    {{ define "jira.summary" }}[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join "," }}{{ end }}

    {{ define "jira.description" }}
    {{ range .Alerts.Firing }}
    Labels:
    {{ range .Labels.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}

    Annotations:
    {{ range .Annotations.SortedPairs }} - {{ .Name }} = {{ .Value }}
    {{ end }}

    Source: {{ .GeneratorURL }}
    {{ end }}

    CommonLabels:
    {{ .CommonLabels.CustomerName }}

    GroupLabels:
    {{ range .GroupLabels.SortedPairs }} - {{ .Name }} = {{ .Value}}
    {{ end }}
    {{ end }}
