name: 'Deploy Hello World'

on:
  push:
    branches: [ main ]
    paths: 
      - .github/workflows/deploy-hello-world.yaml
      - environments/azure/**/apps/hello-world/**
  pull_request:
    branches: [ main ]
    paths: 
      - .github/workflows/deploy-hello-world.yaml
      - environments/azure/**/apps/hello-world/**
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:
    inputs:
      ENV:
        description: 'Environment to deploy'
        type: string
        default: 'dev'
  
env:
  AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  AZURE_RESOURCE_GROUP: "dev-rg-backstage-01"
  AZURE_AKS_CLUSTER_NAME: "dev-aks-bg-01"
  ENV: ${{ github.event.inputs.ENV || 'dev' }}

  
jobs:
  deploy-hello-world:
    name: Deploy Hello World
    runs-on: ubuntu-latest
    # needs: [scan-terraform-config]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: environments/azure/${{ env.ENV }}/apps/hello-world

    steps:
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Print ENV Value
      run: |
        echo "Environment is set to: ${{ env.ENV }}"

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ env.AZURE_CLIENT_ID }}","clientSecret":"${{ env.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZURE_TENANT_ID }}"}'

    - name: Get AKS Credentials
      run: |
        set -e
        az aks get-credentials --resource-group "${{ env.AZURE_RESOURCE_GROUP }}" --name "${{ env.AZURE_AKS_CLUSTER_NAME }}"
        echo "AKS credentials successfully retrieved and context set."

    - name: Verify Kubeconfig Context
      run: |
        if [[ "$(kubectl config current-context)" == *"${{ env.AZURE_AKS_CLUSTER_NAME }}"* ]]; then
          echo "Kubeconfig context is set correctly to ${AZURE_AKS_CLUSTER_NAME}."
        else
          echo "Failed to set kubeconfig context to ${AZURE_AKS_CLUSTER_NAME}." >&2
          exit 1
        fi

    - name: Deploy Hello World
      if: ${{ success() }}
      run: |
        kubectl apply -f ./deployment.yaml
        kubectl apply -f ./service.yaml
        