name: 'Deploy Azure Infrastructure'

on:
  push:
    branches: [ main ]
    paths: .github/workflows/infrastructure-deployment.yaml
  pull_request:
    branches: [ main ]
    paths: .github/workflows/infrastructure-deployment.yaml
  # Allows you to run this workflow manually from the Actions tab 
  workflow_dispatch:
    inputs:
      tfaction: 
        description: 'Terraform Action to Perform'
        default: 'plan'
  
env:
  STORAGE_ACCOUNT_NAME: cloudutsuktfstatestgacc
  RESOURCE_GROUP_NAME: terraform-backend
  RESOURCE_GROUP_LOCATION: centralindia
  CONTAINER_NAME: developer-portal
  TERRAGRUNT_VERSION: 0.68.4
  TERRAFORM_VERSION: v1.9.8
  WORKING_DIRECTORY: environments/azure
  AZURE_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  AZURE_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  
jobs:
  initialize-azure-infra:
    name: Initialize Azure Infrastructure
    runs-on: ubuntu-latest
    environment: development
    # needs: [scan-terraform-config]

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ env.WORKING_DIRECTORY }}

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Repository Checkout
      uses: actions/checkout@v2

    - name: Azure CLI Login
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ env.AZURE_CLIENT_ID }}","clientSecret":"${{ env.AZURE_CLIENT_SECRET }}","subscriptionId":"${{ env.AZURE_SUBSCRIPTION_ID }}","tenantId":"${{ env.AZURE_TENANT_ID }}"}'

    - name: Create Azure Storage Account for Terraform Backend
      run: |
        az account set --subscription "$ARM_SUBSCRIPTION_ID"
        subscriptionName=$(az account show --query name -o tsv)
        echo "Subscription is set to: $subscriptionName"
        # Create resource group
        if [[ $(az group exists --name $RESOURCE_GROUP_NAME) == false ]]; then
          az group create --name $RESOURCE_GROUP_NAME --location $RESOURCE_GROUP_LOCATION \
          --only-show-errors
          echo "Resource group $RESOURCE_GROUP_NAME created."
        else
          echo "Resource group $RESOURCE_GROUP_NAME already exists."
        fi
        
        # Create storage account
        if [[ $(az storage account check-name --name $STORAGE_ACCOUNT_NAME --query 'nameAvailable') == true ]]; then
          az storage account create --name $STORAGE_ACCOUNT_NAME \
              --resource-group $RESOURCE_GROUP_NAME \
              --sku Standard_LRS \
              --encryption-services blob \
              --only-show-errors
          echo "Storage account $STORAGE_ACCOUNT_NAME created."
        else
          echo "Storage account $STORAGE_ACCOUNT_NAME already exists."
        fi
        
        # Create blob container
        if [[ $(az storage container exists --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME --auth-mode login --query 'exists') == false ]]; then
          az storage container create --name $CONTAINER_NAME --account-name $STORAGE_ACCOUNT_NAME --auth-mode login \
          --only-show-errors
          echo "Blob container $CONTAINER_NAME created."
        else
          echo "Blob container $CONTAINER_NAME already exists."
        fi
      env:
        ARM_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}


    - name: Terragrunt hclfmt
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: ${{ env.WORKING_DIRECTORY }}
        tg_command: 'hclfmt --terragrunt-check --terragrunt-diff'
    
    - name: Terragrunt Init
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: ${{ env.WORKING_DIRECTORY }}
        tg_command: 'init'

    - name: Terragrunt Plan
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: ${{ env.WORKING_DIRECTORY }}
        tg_command: 'plan'

    - name: Terragrunt Apply
      uses: gruntwork-io/terragrunt-action@v2
      with:
        tf_version: ${{ env.TERRAFORM_VERSION }}
        tg_version: ${{ env.TERRAGRUNT_VERSION }}
        tg_dir: ${{ env.WORKING_DIRECTORY }}
        tg_command: 'apply'